In [1]:
import torch  # <Ctrl> / <Shift> + <Return>

In [2]:
# Generate a tensor of size 2x3x4
t = torch.Tensor(2, 3, 4)
type(t)

torch.Tensor

In [3]:
# Get the size of the tensor
t.size()

torch.Size([2, 3, 4])

In [4]:
# t.size() is a classic tuple =>
print('t size:', ' \u00D7 '.join(map(str, t.size())))

t size: 2 × 3 × 4


In [5]:
# prints dimensional space and sub-dimensions
print(f'point in a {t.numel()} dimensional space')
print(f'organised in {t.dim()} sub-dimensions')

point in a 24 dimensional space
organised in 3 sub-dimensions


In [6]:
t

tensor([[[ 0.0000e+00,  0.0000e+00,  4.2907e-30,  1.4013e-45],
         [-4.8503e-12,  4.5870e-41, -4.8503e-12,  4.5870e-41],
         [-4.8503e-12,  4.5870e-41,  0.0000e+00,  0.0000e+00]],

        [[ 3.5733e-43,  0.0000e+00, -1.1350e+10,  8.2963e+01],
         [ 7.2128e+22,  1.4071e+25,  6.9765e+22,  3.6727e-41],
         [ 1.4013e-45,  0.0000e+00,  3.5733e-43,  2.7551e-40]]])

In [8]:
# Mind the underscore!
# Any operation that mutates a tensor in-place is post-fixed with an _.
# For example: x.copy_(y), x.t_(), x.random_(n) will change x.
t.random_(10)

tensor([[[3., 3., 2., 0.],
         [1., 4., 8., 8.],
         [8., 3., 6., 9.]],

        [[5., 1., 6., 5.],
         [9., 1., 5., 1.],
         [5., 5., 7., 8.]]])

In [9]:
t

tensor([[[3., 3., 2., 0.],
         [1., 4., 8., 8.],
         [8., 3., 6., 9.]],

        [[5., 1., 6., 5.],
         [9., 1., 5., 1.],
         [5., 5., 7., 8.]]])

In [10]:
# This resizes the tensor permanently 
r = torch.Tensor(t)
r.resize_(3, 8)
r

tensor([[3., 3., 2., 0., 1., 4., 8., 8.],
        [8., 3., 6., 9., 5., 1., 6., 5.],
        [9., 1., 5., 1., 5., 5., 7., 8.]])

In [14]:
# As you can see zero_ would replace r with 0's which was originally filled with integers
r.zero_()

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
t

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
# Copying a tensor
s = r.clone()

In [17]:
# In-place fill of 1's
s.fill_(1)
s

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
# Because we cloned r, even though we did an in-place operation, this doesn't affect r
r

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

## Vectors (1D Tensors)

In [19]:
# Creates a 1D tensor of integers 1 to 4
v = torch.Tensor([1, 2, 3, 4])
v

tensor([1., 2., 3., 4.])

In [20]:
# Print number of dimensions (1D) and size of tensor
print(f'dim: {v.dim()}, size: {v.size()[0]}')

dim: 1, size: 4


In [21]:
w = torch.Tensor([1, 0, 2, 0])
w

tensor([1., 0., 2., 0.])

In [22]:
# Element-wise multiplication
v * w

tensor([1., 0., 6., 0.])

In [23]:
# Scalar product: 1*1 + 2*0 + 3*2 + 4*0
v @ w

tensor(7.)

In [24]:
# In-place replacement of random number from 0 to 10
x = torch.Tensor(5).random_(10)
x

tensor([7., 9., 5., 1., 8.])

In [25]:
print(f'first: {x[0]}, last: {x[-1]}')

first: 7.0, last: 8.0


In [26]:
# Extract sub-Tensor [from:to)
x[1:2 + 1]

tensor([9., 5.])

In [27]:
v

tensor([1., 2., 3., 4.])

In [28]:
# Create a tensor with integers ranging from 1 to 5, excluding 5
v = torch.arange(1, 4 + 1)
v

tensor([1, 2, 3, 4])

In [29]:
# Square all elements in the tensor
print(v.pow(2), v)

tensor([ 1,  4,  9, 16]) tensor([1, 2, 3, 4])


## Matrices (2D Tensors)

In [30]:
# Create a 2x4 tensor
m = torch.Tensor([[2, 5, 3, 7],
                  [4, 2, 1, 9]])
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [31]:
m.dim()

2

In [32]:
print(m.size(0), m.size(1), m.size(), sep=' -- ')

2 -- 4 -- torch.Size([2, 4])


In [33]:
# Returns the total number of elements, hence num-el (number of elements)
m.numel()

8

In [41]:
# Indexing row 0, column 2 (0-indexed)
m[0][2].item()

3.0

In [35]:
# Indexing row 0, column 2 (0-indexed)
m[0, 2]

tensor(3.)

In [36]:
# Indexing column 1, all rows (returns size 2)
m[:, 1]

tensor([5., 2.])

In [37]:
# Indexing column 1, all rows (returns size 2x2)
m[:, [1]]

tensor([[5.],
        [2.]])

In [42]:
# Indexes row 0, all columns (returns 1x4)
m[[0], :]

tensor([[2., 5., 3., 7.]])

In [43]:
# Indexes row 0, all columns (returns size 4)
m[0, :]

tensor([2., 5., 3., 7.])

In [44]:
# Create tensor of numbers from 1 to 5 (excluding 5)
v = torch.arange(1., 4 + 1)
v

tensor([1., 2., 3., 4.])

In [ ]:
m

In [45]:
# Scalar product
m @ v

tensor([49., 47.])

In [46]:
# Calculated by 1*2 + 2*5 + 3*3 + 4*7
m[[0], :] @ v

tensor([49.])

In [47]:
# Calculated by 
m[[1], :] @ v

tensor([47.])

In [48]:
# Add a random tensor of size 2x4 to m
m + torch.rand(2, 4)

tensor([[2.0267, 5.3306, 3.4023, 7.0495],
        [4.9297, 2.9033, 1.0422, 9.0544]])

In [49]:
# Subtract a random tensor of size 2x4 to m
m - torch.rand(2, 4)

tensor([[1.1528, 4.2425, 2.2172, 6.0411],
        [3.2494, 1.6721, 0.6243, 8.6700]])

In [50]:
# Multiply a random tensor of size 2x4 to m
m * torch.rand(2, 4)

tensor([[0.2501, 2.2880, 0.2579, 0.8964],
        [2.8369, 1.5328, 0.0277, 2.8607]])

In [51]:
# Divide m by a random tensor of size 2x4
m / torch.rand(2, 4)

tensor([[ 2.3646,  6.3629,  4.2002, 11.2999],
        [11.1086,  2.1553,  2.5416, 10.7061]])

In [52]:
m.size()

torch.Size([2, 4])

In [53]:
# Transpose tensor m, which is essentially 2x4 to 4x2
m.t()

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

In [54]:
# Same as
m.transpose(0, 1)

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

## Constructors

In [55]:
# Create tensor from 3 to 8, with each having a space of 1
torch.arange(3., 8 + 1)

tensor([3., 4., 5., 6., 7., 8.])

In [56]:
# Create tensor from 5.7 to -2.1 with each having a space of -3
torch.arange(5.7, -2.1, -3)

tensor([ 5.7000,  2.7000, -0.3000])

In [57]:
# returns a 1D tensor of steps equally spaced points between start=3, end=8 and steps=20
torch.linspace(3, 8, 20).view(1, -1)

tensor([[3.0000, 3.2632, 3.5263, 3.7895, 4.0526, 4.3158, 4.5789, 4.8421, 5.1053,
         5.3684, 5.6316, 5.8947, 6.1579, 6.4211, 6.6842, 6.9474, 7.2105, 7.4737,
         7.7368, 8.0000]])

In [58]:
# Create a tensor filled with 0's
torch.zeros(3, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [59]:
# Create a tensor filled with 1's
torch.ones(3, 2, 5)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [60]:
# Create a tensor with the diagonal filled with 1
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Casting

In [61]:
# This is basically a 64 bit float tensor
m_double = m.double()
m_double

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]], dtype=torch.float64)

In [62]:
# This creates a tensor of type int8
m_byte = m.byte()
m_byte

tensor([[2, 5, 3, 7],
        [4, 2, 1, 9]], dtype=torch.uint8)

In [63]:
# Move your tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m.to(device)

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [64]:
# Converts tensor to numpy array
m_np = m.numpy()
m_np

array([[2., 5., 3., 7.],
       [4., 2., 1., 9.]], dtype=float32)

In [65]:
# In-place fill of column 0 and row 0 with value -1
m_np[0, 0] = -1
m_np

array([[-1.,  5.,  3.,  7.],
       [ 4.,  2.,  1.,  9.]], dtype=float32)

In [66]:
m

tensor([[-1.,  5.,  3.,  7.],
        [ 4.,  2.,  1.,  9.]])

In [67]:
# Create a tensor of integers ranging from 0 to 4
import numpy as np
n_np = np.arange(5)
n = torch.from_numpy(n_np)
print(n_np, n)

[0 1 2 3 4] tensor([0, 1, 2, 3, 4])


In [68]:
# In-place multiplication of all elements by 2 for tensor n
# Because n is essentiall n_np, not a clone, this affects n_np
n.mul_(2)
n_np

array([0, 2, 4, 6, 8])